# Chapter 5. 시각화

## [준비작업]한글폰트 설치 및 설정

In [ ]:
#1. 현재 셀 실행
#2. 런타임 -> 세션 다시 시작
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [ ]:
plt.rc('font', family='NanumBarunGothic')

## 1. 붓꽃 데이터 활용

- sns.load_dataset()으로 붓꽃(아이리스) 데이터를 불러와 그래프를 그려보자.
- 붓꽃 데이터는 시각화에서 유명한 데이터라 seaborn에 데이터셋으로 들어가 있다. 이 외에도 titanic, tips, penguins, flights, diamonds 등이 있다.
- .head()로 붓꽃 데이터의 다섯 개 행의 정보를 확인해보자.
- 붓꽃 데이터 열의 의미는 다음과 같다.
  - sepal_length : 꽃받침 길이
  - sepal_width : 꽃받침 너비
  - petal_length : 꽃잎 길이
  - petal_width : 꽃잎 너비
  - species : 아이리스 종류(setosa, versicolor, virginica)

In [ ]:
import seaborn as sns
iris = sns.load_dataset("iris") #iris(붓꽃)데이터셋
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### 1-1. pairplot 그래프: .pairplot()
- **pairplot그래프**는 데이터프레임의 열(변수)을 두 개씩 짝을 지을 수 있는 모든 조합에 대해 나타낸다.
- 만들어진 짝의 개수만큼 화면을 그리드로 나눈다.
- 같은 변수끼리 짝을 이루는 경우에는 **커널밀도 그래프**로 나타내고, 서로 다른 변수 간에는 **산점도 그래프**를 나타낸다.
- 옵션 `hue`는 카테고리별로 보여준다.

😄 붓꽃 데이터의 붓꽃 종류별 4가지(꽃받침, 꽃잎의 길이와 너비) 조합에 대해 pairplot()을 그려보자.이때 품종별로 색상을 보여주자.

<div align="center"><img src="https://haesunbyun.github.io/common/images/bb_prac1.PNG" width=500></div>

### 1-2. FacetGrid 그래프: .FacetGrid()
- **FacetGrid그래프**는 행, 열 방향으로 서로 다른 조건을 적용하여 여러 개의 서브 플롯을 만든다.
- map() 함수를 이용하여 각 서브 플롯에 적용할 그래프 종류를 전달한다.
- 😄 붓꽃 종류(품종)별로 열방향으로 그리드를 나눠 히스토그램을 그려보자. 이때 품종별로 색상을 보여주자.

<div align="center"><img src="https://haesunbyun.github.io/common/images/bb_prac2.PNG" width=500></div>

## 2. 팁스 데이터 활용

- 팁스 데이터를 활용하여 그래프를 그려보자.
  - total_bill: 식사금액
  - tip: 팁금액
  - sex: 성별
  - smoker: 흡연여부
  - day: 요일
  - time: 점심/저녁

In [ ]:
import seaborn as sns
tips = sns.load_dataset("tips")
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### 표현할 그래프 생각해보기

- tips 데이터프레임을 보고 표현할 그래프를 생각해봅시다.
  - 요일별 total_bill의 평균
  - 요일별 빈도(count)
  -  'total_bill'과 'tip'간의 관계
  - 성별별 'total_bill'과 'tip'간의 관계
  - 시간대별 total_bill의 분포
  - 시간대&흡연여부에 따른 total_bill과 tip의 관계
  - total_bill의 분포(히스토그램)
  - 성별별 tip의 분포(박스플롯)
  - total_bill과 tip간의 분포(산포도)

### 2-1. 막대 그래프: .barplot()
- 😄 요일별 total_bill의 평균을 막대그래프를 그려보자.

<div align="center"><img src="https://haesunbyun.github.io/common/images/barchart.png" width="400">
</div>

### 2-2. count 그래프: .countplot()
- 고유한 값이나 범주 수가 제한된 변수(예: 성별 또는 종교)인 범주형 변수의 빈도수를 시각화하여 보여주는 그래프이다.
- 😄 요일별 빈도수를 그래프로 그려보자.

<div align="center"><img src="https://haesunbyun.github.io/common/images/count.png" width="400">
</div>

- `hue`옵션을 통해 카테고리별로 그릴 수 있다.
- 😄 시간(lunch, dinner)을 카테고리로 줘서 요일별 빈도수를 그래프로 그려보자.

<div align="center"><img src="https://haesunbyun.github.io/common/images/counthue.png" width="400">
</div>

### 2-3. 회귀선이 있는 산포도 그래프: regplot()
- 산포도와 선형회귀분석에 의한 회귀선, 95%의 신뢰구간을  함께 나타내는 그래프이다.
  - 회귀선: 산포도에 산재해 있는 점들의 관계에 근거하여 그어지는 선
  - 회귀선 위아래 음영처리 된 부분이 신뢰구간이다.
- 😄 'total_bill'과 'tip'간의 관계를 보기위해 회귀선이 있는 산포도 그래프를 그려보자.
<div align="center"><img src="https://haesunbyun.github.io/common/images/regplot.png" width="400">
</div>

### 2-4. 카테고리별 회귀선이 있는 산포도 그리기: lmplot()
- regplot()과 비슷하나, hue 파라미터를 지정하여 카테고리별로 각각 데이터의 분포와 선형 관계를 표시할 수 있다.
- 😄 성별을 카테고리로 줘서 'total_bill'과 'tip'간의 관계를  회귀선이 있는 산포도 그래프를 그려보자.

<div align="center"><img src="https://haesunbyun.github.io/common/images/lmplot.png" width="400">
</div>

### 2-5. 시간대별 total_bill의 분포: FacetGrid()

FacetGrid() 함수를 사용하여 도화지를 분할하고, tips 에서 시간대별 total_bill의 값을 보여주는 히스토그램 그래프를 나타내시오. 그래프를 통해 무엇을 설명할 수 있는지도 생각해보시오.

FacetGrid()를 사용하면 matplotlib의 subplot()처럼 row, column, index를 하나 하나 설정해줄필요가 없다.

<div align="center"><img src="https://haesunbyun.github.io/common/images/visual6.png" style="width:400px;">
</div>

### 2-7. 시간대와 흡연여부에 따른 total_bill과 tip의 관계
😄 FacetGrid() 함수를 사용하여 도화지를 분할하고, tips 에서 시간대와 흡연여부에 따른 total_bill과 tip의 관계를 보여주는 산포도 그래프를 나타내시오.
무엇을 설명할 수 있는지도 생각해보시오.

<div align="center"><img src="https://haesunbyun.github.io/common/images/visual5.png" style="width:400px;">
</div>

## 3. 도서관 데이터 활용

#### 3-1. 가장 많이 휴관하는 요일

😄 경기도 수원에 거주하고 있는 혜원이는 수원시 관내에 존재하는 도서관들이 어떤 요일에 가장 많이 휴관하는지 알고 싶어졌다.

Matplotlib 및 Seaborn을 이용하여, library_suwon.csv 파일 내에 존재하는 수원시 도서관들이 어느 요일에 가장 많이 휴관하는지 찾으시오.

단, 원본 DataFrame을 수정할 수 없다.
링크는 다음과 같다.
https://raw.githubusercontent.com/HaesunByun/common/main/data/library_suwon.csv

#### 3-2. 열람좌석 수, 장서 수
😄 수원시 내 도서관 몇 군데를 둘러보던 혜원이는 다음과 같은 가설을 세우게 되었다.

"열람 좌석 수가 많은 곳은, 장서 수도 많지 않을까?"

해원이의 가설이 (가) 공공도서관 (나) 어린이도서관 각각에 대하여 성립하는지 개별적으로 검증하시오.

단, 검증 과정에서 두 개 이상의 plot을 출력해서는 안 된다.
링크는 문제 도서관 I과 같다.

## 4.비만도 데이타

😄 비만도 데이터를 확인하고 어떤 그래프를 그리는 것이 적합한지 확인하여 적절한 그래프를 그려보세요.

In [ ]:
bmiDF=pd.read_csv('https://raw.githubusercontent.com/HaesunByun/common/main/data/bmiDF.csv')
bmiDF

## 5. 월별 교통사고 시각화
😄 월별 교통사고 데이터를 확인하고 어떤 그래프를 그리는 것이 적합한지 확인하여 적절한 그래프를 그려보세요. <br>

In [ ]:
url= 'https://raw.githubusercontent.com/HaesunByun/common/main/data/drivingDF.csv'
drivingDF = pd.read_csv(url, index_col = 0)
drivingDF.sort_index(ascending=True, inplace=True)
drivingDF